name: Run On This Day

on:
  schedule:
    - cron: '25 15 * * *'

jobs:
  on-this-day:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo TWITTER_APP_KEY=${{ secrets.TWITTER_APP_KEY }} >> .env
          echo TWITTER_APP_SECRET=${{ secrets.TWITTER_APP_SECRET }} >> .env
          echo TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }} >> .env
          echo TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }} >> .env
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Deps
        run: npm install --omit=dev
      - name: Run Task
        run: node ./tasks/OnThisDay.js
